### ISSUE TITLE
printing formatted numbers above 2^54 breaks

### ISSUE THREAD

**Issue by Gumnos** [marcopaganini/rpn#13]
While the internal math seems to successfully handle the arbitrary-precision tests I threw at it such as 2^65, the comma-formatting is off:

    $ ./rpn
    2 65 ^ 
    = 36893488147419103232 (36,893,488,147,419,103,000)

Note that the actual answer ends in "232" while the formatted answer ends in "000".  There seems to be something between 2^54 and 2^55 that breaks the formatting:

    2 54 ^
    = 18014398509481984 (18,014,398,509,481,984)
    2 55 ^
    = 36028797018963968 (36,028,797,018,963,970)

**Comment by marcopaganini** [comment]
This is an interesting problem, thanks for reporting.

We're using the [humanize](https://github.com/dustin/go-humanize) library to format large numbers. Looking at humanize's source code, I see it calls `strconv.FormatFloat` using precision = -1. From the `strconv.FormatFloat` documentation:

> The special precision -1 uses the smallest number of digits
> necessary such that ParseFloat will return f exactly.

64-bit floating point numbers have an effective resolution of 53 bits. Wikipedia has the following interesting comments on the float64 limitations:

> Precision limitations on integer values
>
> Integers from −253 to 253 (−9,007,199,254,740,992 to 9,007,199,254,740,992) can be exactly represented.
> Integers between 253 and 254 = 18,014,398,509,481,984 round to a multiple of 2 (even number).
> Integers between 254 and 255 = 36,028,797,018,963,968 round to a multiple of 4.
> Integers between 2n and 2n+1 round to a multiple of 2n−52.

It also says that it should be possible to represent numbers up to 17 digits without rounding errors.

Bringing back your original message:

```
$ ./rpn
2 65 ^ 
= 36893488147419103232 (36,893,488,147,419,103,000)
```

Notice how `strconv.FormatFloat` trims at the 17th digit. IIUC, this is because when we use precision -1 we're effectively saying "Just show the exact representation, without rounding".

This is easy to fix, but will return less than exact numbers when we're talking more than 17 digits. Setting "prec" to 0 when calling `strconv.FormatFloat` will do that and match the results we see in dc, for example.

Naturally, there's a limit on how large a float64 can be. If super large numbers become a popular niche use for this program, we'll have to consider converting everything to big.Float.

**Comment by marcopaganini** [comment]
BTW, here's a simple program showing the problem: https://go.dev/play/p/1hqoar6qKYv

**Comment by Gumnos** [comment]
no worries…it's just one of the main reasons that I use `bc(1)`/`dc(1)`, to get arbitrary precision.

Just might be worth mentioning as part of the comparison with `dc`

**Comment by marcopaganini** [comment]
Yes! I'll add that difference to the README.md.

BTW, I just quickly hacked v0.3.1 that should fix the command printing of large (but not too large) numbers. 2 ^ 64 should work now.

Could you please give it a shot and let me know if it works for you?

**Comment by Gumnos** [comment]
LGTM, I can confirm that at least the formatted and unformatted output now match.

**Comment by marcopaganini** [comment]
Thanks a lot!

BTW, I took another look at  "decimal" (arbitrary precision library) and it shouldn't be so hard to convert. Expect some news soon :)

I'm marking this bug as closed.
